---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-organization-opendatahub-io-v1alpha1-maasconfiguration
  failurePolicy: Fail
  name: vmaasconfiguration-v1alpha1.kb.io
  rules:
  - apiGroups:
    - organization.opendatahub.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - maasconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-organization-opendatahub-io-v1alpha1-organization
  failurePolicy: Fail
  name: vorganization-v1alpha1.kb.io
  rules:
  - apiGroups:
    - organization.opendatahub.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - organizations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-organization-opendatahub-io-v1alpha1-organizationprofile
  failurePolicy: Fail
  name: vorganizationprofile-v1alpha1.kb.io
  rules:
  - apiGroups:
    - organization.opendatahub.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - organizationprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-organization-opendatahub-io-v1alpha1-organizationproject
  failurePolicy: Fail
  name: vorganizationproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - organization.opendatahub.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - organizationprojects
  sideEffects: None
