apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maasconfiguration-editor-role
rules:
- apiGroups: [organization.opendatahub.io]
  resources: [maasconfigurations]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [organization.opendatahub.io]
  resources: [maasconfigurations/status]
  verbs: [get]
