apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maasconfiguration-admin-role
rules:
- apiGroups: [organization.opendatahub.io]
  resources: [maasconfigurations, maasconfigurations/status]
  verbs: [get, list, watch, create, update, patch, delete]
