---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - edit
  - view
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.opendatahub.io
  resources:
  - platformtenants
  - tenantprofiles
  - tenantprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.opendatahub.io
  resources:
  - platformtenants/status
  - tenantprofiles/status
  - tenantprojects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tenancy.opendatahub.io
  resources:
  - tenantprofiles/finalizers
  verbs:
  - update
