apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantmaas-editor-role
rules:
- apiGroups: [tenancy.opendatahub.io]
  resources: [tenantmaases]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [tenancy.opendatahub.io]
  resources: [tenantmaases/status]
  verbs: [get]
