## Append samples of your project ##
resources:
- tenancy_v1alpha1_organization.yaml
- tenancy_v1alpha1_organizationprofile.yaml
- tenancy_v1alpha1_organizationproject.yaml
- tenancy_v1alpha1_maasconfiguration.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
