//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSCertificateRef) DeepCopyInto(out *MaaSCertificateRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSCertificateRef.
func (in *MaaSCertificateRef) DeepCopy() *MaaSCertificateRef {
	if in == nil {
		return nil
	}
	out := new(MaaSCertificateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSGateway) DeepCopyInto(out *MaaSGateway) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSGateway.
func (in *MaaSGateway) DeepCopy() *MaaSGateway {
	if in == nil {
		return nil
	}
	out := new(MaaSGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSOIDC) DeepCopyInto(out *MaaSOIDC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSOIDC.
func (in *MaaSOIDC) DeepCopy() *MaaSOIDC {
	if in == nil {
		return nil
	}
	out := new(MaaSOIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSQuotas) DeepCopyInto(out *MaaSQuotas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSQuotas.
func (in *MaaSQuotas) DeepCopy() *MaaSQuotas {
	if in == nil {
		return nil
	}
	out := new(MaaSQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSService) DeepCopyInto(out *MaaSService) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(MaaSOIDC)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(MaaSGateway)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(MaaSTLS)
		**out = **in
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(MaaSQuotas)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSService.
func (in *MaaSService) DeepCopy() *MaaSService {
	if in == nil {
		return nil
	}
	out := new(MaaSService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSStatus) DeepCopyInto(out *MaaSStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSStatus.
func (in *MaaSStatus) DeepCopy() *MaaSStatus {
	if in == nil {
		return nil
	}
	out := new(MaaSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSTLS) DeepCopyInto(out *MaaSTLS) {
	*out = *in
	out.CertificateRef = in.CertificateRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSTLS.
func (in *MaaSTLS) DeepCopy() *MaaSTLS {
	if in == nil {
		return nil
	}
	out := new(MaaSTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformTenant) DeepCopyInto(out *PlatformTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformTenant.
func (in *PlatformTenant) DeepCopy() *PlatformTenant {
	if in == nil {
		return nil
	}
	out := new(PlatformTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformTenantList) DeepCopyInto(out *PlatformTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformTenantList.
func (in *PlatformTenantList) DeepCopy() *PlatformTenantList {
	if in == nil {
		return nil
	}
	out := new(PlatformTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformTenantSpec) DeepCopyInto(out *PlatformTenantSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformTenantSpec.
func (in *PlatformTenantSpec) DeepCopy() *PlatformTenantSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformTenantStatus) DeepCopyInto(out *PlatformTenantStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformTenantStatus.
func (in *PlatformTenantStatus) DeepCopy() *PlatformTenantStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDefaults) DeepCopyInto(out *ProjectDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDefaults.
func (in *ProjectDefaults) DeepCopy() *ProjectDefaults {
	if in == nil {
		return nil
	}
	out := new(ProjectDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUser) DeepCopyInto(out *ProjectUser) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUser.
func (in *ProjectUser) DeepCopy() *ProjectUser {
	if in == nil {
		return nil
	}
	out := new(ProjectUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subject) DeepCopyInto(out *Subject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfile) DeepCopyInto(out *TenantProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfile.
func (in *TenantProfile) DeepCopy() *TenantProfile {
	if in == nil {
		return nil
	}
	out := new(TenantProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfileList) DeepCopyInto(out *TenantProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfileList.
func (in *TenantProfileList) DeepCopy() *TenantProfileList {
	if in == nil {
		return nil
	}
	out := new(TenantProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfileSpec) DeepCopyInto(out *TenantProfileSpec) {
	*out = *in
	if in.Admins != nil {
		in, out := &in.Admins, &out.Admins
		*out = make([]Subject, len(*in))
		copy(*out, *in)
	}
	out.Defaults = in.Defaults
	in.Services.DeepCopyInto(&out.Services)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfileSpec.
func (in *TenantProfileSpec) DeepCopy() *TenantProfileSpec {
	if in == nil {
		return nil
	}
	out := new(TenantProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfileStatus) DeepCopyInto(out *TenantProfileStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	out.MaaS = in.MaaS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfileStatus.
func (in *TenantProfileStatus) DeepCopy() *TenantProfileStatus {
	if in == nil {
		return nil
	}
	out := new(TenantProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProject) DeepCopyInto(out *TenantProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProject.
func (in *TenantProject) DeepCopy() *TenantProject {
	if in == nil {
		return nil
	}
	out := new(TenantProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProjectList) DeepCopyInto(out *TenantProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProjectList.
func (in *TenantProjectList) DeepCopy() *TenantProjectList {
	if in == nil {
		return nil
	}
	out := new(TenantProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProjectSpec) DeepCopyInto(out *TenantProjectSpec) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]ProjectUser, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProjectSpec.
func (in *TenantProjectSpec) DeepCopy() *TenantProjectSpec {
	if in == nil {
		return nil
	}
	out := new(TenantProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProjectStatus) DeepCopyInto(out *TenantProjectStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProjectStatus.
func (in *TenantProjectStatus) DeepCopy() *TenantProjectStatus {
	if in == nil {
		return nil
	}
	out := new(TenantProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantServices) DeepCopyInto(out *TenantServices) {
	*out = *in
	if in.MaaS != nil {
		in, out := &in.MaaS, &out.MaaS
		*out = new(MaaSService)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantServices.
func (in *TenantServices) DeepCopy() *TenantServices {
	if in == nil {
		return nil
	}
	out := new(TenantServices)
	in.DeepCopyInto(out)
	return out
}
